import { useState } from 'react';
import { MoreHorizontal, Plus, RotateCcw, Search, ShoppingCart } from 'lucide-react';
import { Badge, Button, Modal, PageHeader } from '../components/ui';

export default function Procurement({ requests, setRequests, notify }) {
  const [modal, setModal] = useState(false);
  const submit = (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); setRequests((current) => [{ id: `PR-00${29 + current.length}`, item: form.get('item'), requester: 'Ananya Sen', department: 'Operations', priority: form.get('priority'), status: 'Draft', cost: form.get('cost') || 'Not quoted', date: 'Just now' }, ...current]); setModal(false); notify('Procurement request saved as draft.'); };
  return <div className="page-stack"><PageHeader eyebrow="Operations / Procurement" title="Procurement" description="Search existing inventory first, then move new purchases through approval." action={<Button icon={Plus} onClick={() => setModal(true)}>New request</Button>} /><div className="procurement-banner"><div className="banner-icon"><ShoppingCart size={20} /></div><div><strong>Inventory-first workflow</strong><span>Before raising a purchase, search available and assigned assets to avoid unnecessary spend.</span></div><Button variant="secondary" onClick={() => setModal(true)}>Search inventory</Button></div><div className="panel"><div className="filter-tabs"><button className="active">All requests</button><button>My requests</button><button>Needs approval <span className="tab-count">3</span></button><button>Ordered</button></div><div className="table-wrap"><table><thead><tr><th>Request</th><th>Requested by</th><th>Priority</th><th>Status</th><th>Estimated cost</th><th>Created</th><th /></tr></thead><tbody>{requests.map((request) => <tr key={request.id}><td><div><strong className="mono">{request.id}</strong><span className="cell-subtitle">{request.item}</span></div></td><td><div><strong>{request.requester}</strong><span className="cell-subtitle">{request.department}</span></div></td><td><Badge>{request.priority}</Badge></td><td><Badge>{request.status}</Badge></td><td>{request.cost}</td><td className="muted-cell">{request.date}</td><td><button className="row-action"><MoreHorizontal size={17} /></button></td></tr>)}</tbody></table></div></div>{modal && <Modal title="Raise procurement request" onClose={() => setModal(false)}><form className="form-grid" onSubmit={submit}><label>Item name<input name="item" required placeholder="What do you need?" /></label><label>Request type<select><option>New purchase</option><option>Existing asset</option></select></label><label>Priority<select name="priority"><option>Normal</option><option>Low</option><option>High</option><option>Critical</option></select></label><label>Estimated cost<input name="cost" placeholder="₹0.00" /></label><label className="full-field">Justification<textarea required minLength="20" placeholder="Tell us why this request is needed..." /></label><div className="modal-actions"><Button variant="secondary" onClick={() => setModal(false)}>Cancel</Button><Button type="submit">Save request</Button></div></form></Modal>}</div>;
}
